### ISSUE TITLE
Скрипт для настройки asset whitelist

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#11]
**[bounty: 5 UTDEV]**

Задача: настроить наш основной инвестиционный токен UTCORE на обращение строго по whitelist с целью ограничения круга его держателей членами совета директоров U-TECH и лицами, получившими доступ к специальным предложениям (например, держатели UTDEV, сэкономившие его "на завтраках").

Есть кое какая информация на этот счет, полученная из "первых рук":
Abit More, [30 Aug 2017, 13:14]:
perhaps you misunderstood it
check get_asset ICOWT
there are two layers
define whitelist-authorities (admin accounts) in asset, then define the real lists in the admin accounts
for example, get_asset ICOWT shows one of the admins is "1.2.351639", and get_account "1.2.351639" shows the real white list

Konstantin, [30 Aug 2017, 13:21]:
oh thanks. I'll give it a try. but can I set up asset restrictions via GUI or not? May be I should issue asset _after_ making changes to whitelist?

Abit More, [30 Aug 2017, 13:56]:
no GUI
only works with CLI
in addition, if set something in CLI, then update something in GUI, the settings done in CLI will be overwritten
so, once used CLI, never use GUI again.

**Comment by cptn-solo** [comment]
@UspenskyDritry - готов выслушать встречные предложения :) (напоминаю, UTDEV сейчас стоит в обратном выкупе по $1/UTDEV)
Ну, и понятно, что сначала @mparkhomenko поднять нам ноду.

**Comment by DmitryUspensky** [comment]
@kkrupovich, нашел кусок документации по добавлению/удалению в white/black list юзеров. То что нам нужно собственно, вот ссылка (http://docs.bitshares.org/integration/asset-whitelist.html). Нужен список учеток акционеров для добавления в white list.

**Comment by cptn-solo** [comment]
Было бы неплохо сделать небольшую админку для вайт-листинга (авторизовать администратора, принять имя учетки включаемое в белый список, показать текущий белый список, удалить из белого списка)

**Comment by cptn-solo** [comment]
@UspenskyDritry если есть какие-то рабочие варианты скрипта - просьба создать бранч (в репе codebase) и залить - потом поиграемся с пул-реквестами.
Полагаю, бранч для фичи, (whitelisting?) поэтому в папку whitelisting заливать файлы, относящиеся к задаче (скрипты, код админки)

**Comment by cptn-solo** [comment]
@UspenskyDritry коллега, ссылку(и) на результат(ы) в коммент и закрывай

**Comment by DmitryUspensky** [comment]
@kkrupovich, готовый скрипт можно взять по [ссылке](https://github.com/u-transnet/codebase/wiki/%D0%A1%D0%BA%D1%80%D0%B8%D0%BF%D1%82-%D0%B4%D0%BB%D1%8F-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B8-asset-whitelist) и посмотреть результат на примере [транзакции](https://testnet.bitshares.eu/block/11429905).

**Comment by DmitryUspensky** [comment]
Я заведу таску на будующее, тоже считаю что нам нужна админка для всех скриптов. Иначе скрипты сложно использовать.
