### ISSUE TITLE
Определиться с метриками сервера и выбрать площадку для размещения/аренды

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#12]
Судя по всему, нужно примерно то же самое, что и для Bitshares, т.к. мы первое время все равно не поймем в какую сторону сдвинутся потребности целевого движка - будет ли он более прожорлив, или нам удастся что-то оптимизировать. Но в процессе развертывания ноды Bitshares (полной) важно определиться с разумным уровнем производительности для сервера под целевой блокчейн. 
На выходе этой задачи надо получить ссылки или однозначное описание предложения от провайдера(ов) VPS (ориентировочно www.digitalocean.com)
Результат исследований надо зафиксировать [тут](/u-transnet/codebase/wiki/Требования-к-железу-для-BitShares-witness-node)

**Comment by cptn-solo** [comment]
@mparkhomenko я правильно понял, что мы решили остановиться пока на 8GB с возможностью дальнейшего апгрейда?

**Comment by ghost** [comment]
@kkrupovich да
Droplet на digitalocean c 8GB RAM + 80GB SSD.
При ограничениях в хранении истории этого хватит для ноды Bitshares, а для старта нашего генезиса этого более чем за глаза.

**Comment by ghost** [comment]
@kkrupovich 
[Требования к железу для BitShares witness node](https://github.com/u-transnet/codebase/wiki/%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-%D0%B6%D0%B5%D0%BB%D0%B5%D0%B7%D1%83-%D0%B4%D0%BB%D1%8F-BitShares-witness-node)
