### ISSUE TITLE
Определиться с параметрами генезиса целевого блокчейна - какие есть, на какие надо обратить внимание

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#15]
Название токена базового актива UTT
Остальное надо смотреть и обсуждать в комментариях к задаче

**Comment by cptn-solo** [comment]
@mparkhomenko @alecvert 
про целевой блокчейн могу пока только сказать, что базовый актив называется UTT (Unified Transaction Token). Какой объем, какая дробная часть - без понятия, т.ч. можно брать либо максимальные значения, либо посмотрть чего у BTS (по разрядности точно лучше взять как у BTS - меньше проблем с конверсией потом будет.

**Comment by cptn-solo** [comment]
@mparkhomenko давай сюда вопросы попробуем сформулировать к файлу генезиса? Но что-нибудь более реальное, чем "что это вообще такое". Возможно надо процитировать параметры (все, либо только спорные/интересные) - и выбрать формат обсуждения (гуглодок?)

**Comment by ghost** [comment]
Скилую первую итерацию: изучу параметры, выделю известные, непонятные, полезные и вопросы куда капать дальше...

BLOCK #23849962
map-13
150UTDEV.SKILL
к утру 27.01.18

**Comment by ghost** [comment]
К утру 01.02.18, перенеслось на сегодня, рассчитывал на выходных заняться, не вышло.
