### ISSUE TITLE
Собрать в кучу документацию по подключению фасета (tapin)

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#16]
Есть что-то в заметках от прошлых экспериментов, которые мы с Женей О. проводили, плюс прошерстить телеграм чатов с Женей, возможно, выгрузить их куда-то  

Изначально tapin мы брали отсюда:
github.com/xeroc/tapin

Но теперь его там нет. 
Кроме того, вообще я не в курсе - нужно ли что-то городить вокруг фасета если форкаешь не графен, а bitshares. @mparkhomenko это надо выяснить в процессе развертывания.

**Comment by cptn-solo** [comment]
Например:
параметры в конструктор поступают все. и все они из config.yml
сейчас исходники bitshares py загляну
https://github.com/xeroc/python-bitshares/blob/master/bitsharesapi/bitsharesnoderpc.py
83 строка
в этом методе валится эксепшн
потому что не находит цепочку из known_chains по chain_id
решил посмотреть что за known_chains
https://github.com/xeroc/python-bitshares/blob/master/bitsharesbase/chains.py
и их тут оказывается всего 5 и они захардожены

**Comment by cptn-solo** [comment]
Или вот:
you can make it compatible by providing the chain id .. that's all that makes graphene instances different from bitshares .. (and the prefix and core symbol)

это про либу, дядька ;) мы нашли

you mean in tapin config? (can see config.yml file under tapin sources directory)
but should it work with pure graphene node, not bitshares node?
exactly .. but you need to find out the chain-id
.. and the prefix (default: `GPH`) and core symbol (default also `GPH`)

**Comment by cptn-solo** [comment]
вообще кстати логично. GPH - это префикс, а сам токен - уже атрибут блокчейна конкретной реализации

у нас - CORE, у битшар - BTS

у стима - STEEM

а префикс общий

**Comment by cptn-solo** [comment]
это я пока так настроил. Я понял кстати почему в примере юзался юникс-сокет

запускать через runserver это не самый надежный способ + не самый эффективный

в дальнейшем нужно будет запускать фасет через сервер приложений uwsgi

**Comment by cptn-solo** [comment]
Это тоже просто выдержка из чата, не факт, что это важно. Просто решил процитировать:

в общем, проверенный спелл такой:
cd ~/tapin
pip3 install flask
virtualenv flask
cd flask
source bin/activate
cd ~/tapin
pip3 install -r requirements.txt
python3 manage.py install
python3 manage.py runserver --host=0.0.0.0

**Comment by cptn-solo** [comment]
А это самый первый чат с Fabian Schuh, из которого я прознал про тапин (альтернатива фасета на руби):

github.com/xeroc/tapin ... is a python based faucet that supports cors

nice, that seems easier :)

Fabian, sure, i have tried to fix the CORS issue, but it would be far mor easier if someone pointed out a place the CORS issue happens for. As far as I can see, graphene-ui is deployed to it's one nodejs environment. On the other hand, faucet is deployed on it's own nginx instance, am I right?

sure, but it is not for graphene, it is for bitshares configuration, (IMHO)

I just have no bitshares runtime for tapin in my configuration, because i'm actually trying to run "pure" graphene node

The CORS thing is something that needs fixing in the faucet code .. no clue how that works with ruby/rails...

in tapin, this happens here: https://github.com/xeroc/tapin/blob/master/app/__init__.py#L49

in tapin, this happens here: https://github.com/xeroc/tapin/blob/master/app/__init__.py#L49

if you want to connect the facuet to a different network you need to specify that chain extra in the config.yaml file ..

i.e.:

prefix: "BTS"
chain:
    chain_id:
"a8a61755aaa9d2c19a5989490bbc4195f37f147be3db3dddcf0e06d373b397ce"
    core_symbol: "BTS"
    prefix: "BTS"

you mean in tapin config? (can see config.yml file under tapin sources directory)

but should it work with pure graphene node, not bitshares node?

exactly .. but you need to find out the chain-id

.. and the prefix (default: `GPH`) and core symbol (default also `GPH`)

ok, Fabian, but what should I do with bitshares libraries included in  tapin code? just install them as it required by tapin configuration?

blockchain id is not a problem. The problem with tapin is actually a misunderstanding of the bitshares lib it uses in it's code. I have even deployed it once on my node, but finally decided it is not suited for pure graphene node integration

not compatible

another question is, the faucet itself (say, tapin, or generic faucet from graphene git repo) - is it simply a web-app to serve api calls from graphene-ui (from client side, for sure) and has no GUI at all? and api calls from the "wallet api calls" section in docs, am i right?

in other words, this software (tapin, or faucet) just wraps ajax calls from user's browser to [programs/cli_wallet/cli_wallet --rpc-http-endpoint="127.0.0.1:8092"] ?

you can make it compatible by providing the chain id .. that's all that makes graphene instances different from bitshares .. (and the prefix and core symbol)

API calls only ..

I get the point with chain id. I just wonder what to do with bitshares library dependency.

should I just get it from bitshares repo and integrate with tapin?

pybitshares is a library that deals with graphene code ..but links to bitshares and the testnet .. as well as some other graphene blockchains that haven't changed too much ..

https://github.com/xeroc/python-bitshares/blob/master/bitsharesbase/chains.py

if you want to use a graphene-chain that is not bitshares, nor testnet, you need those parameters ..

ok. Thank you, Fabian, I'll give it another try.

**Comment by cptn-solo** [comment]
@mparkhomenko колега, сошлись пож-та в комменте на результирующий документ в вики и закрывай, чтоле

**Comment by cptn-solo** [comment]
Konstantin, [04.11.17 13:15]
[Forwarded from 0notole Vassermane]
https://github.com/blckchnd/tapin/commit/19df5e1628acdefb0e30da28bc1a714c87f86ba0

Konstantin, [04.11.17 13:17]
[Forwarded from 0notole Vassermane]
В конфиге прописываешь ключ своего ltm

Konstantin, [04.11.17 13:17]
[Forwarded from 0notole Vassermane]
Запускаешь Start.sh

Konstantin, [04.11.17 13:17]
[Forwarded from 0notole Vassermane]
посылаешь curl'ом запрос на http://localhost:9090/api/v1/accounts

Konstantin, [04.11.17 13:18]
[Forwarded from 0notole Vassermane]
останется настроить в nginx проксирование на локальный 9090 порт

Konstantin, [04.11.17 13:20]
[Forwarded from 0notole Vassermane]
Вот какой конфиг у нас

location /api
  {
          if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
         }

    proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_cache_bypass $http_upgrade;
          proxy_pass http://127.0.0.1:9090/api;
        }

**Comment by ghost** [comment]
@kkrupovich 
[Развертка и применение faucet "tapin"](https://github.com/u-transnet/codebase/wiki/%D0%A0%D0%B0%D0%B7%D0%B2%D0%B5%D1%80%D1%82%D0%BA%D0%B0-%D0%B8-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-faucet-%22tapin%22)
