### ISSUE TITLE
Адаптация докера от Bitshares witness под u-transnet witness

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#17]
На вход результат задачи #8

**Comment by cptn-solo** [comment]
У нас есть образец, rudex, надо попробовать собрать что-то на его основе
https://github.com/blckchnd/tapin/commit/19df5e1628acdefb0e30da28bc1a714c87f86ba0
Там, правда, про фасет, главным образом, но мало ли, чем-то поможет

**Comment by ghost** [comment]
Нужно сделать два Dockerfile: один для автономной сборки, как уже сделано под битшару, второй вариант - это адаптация отсталого Dockerfile, чтобы собирать из исходников рядом, нужно при этом не минимизировать размер image, упор сделать на скорость сборки при изменении сорсов.

**Comment by ghost** [comment]
BLOCK #22417619
map-13
300UTDEV.SKILL
до вечера 07.12.2017

**Comment by ghost** [comment]
@kkrupovich 
[Dev вариант dockerfile](https://github.com/u-transnet/utransnet-core/commit/8ebd6e20c0b13d6a3191421d3384931698a6c8de)
[Release вариант dockerfile](https://github.com/u-transnet/dockerfiles/blob/master/utransnet-core)
Нужно разобраться будет в дальнейшем с тем, чтобы прописать нашу основную ноду, дабы новые ноды могли ее видеть и с ней синхронизироваться.

**Comment by cptn-solo** [comment]
> Нужно разобраться будет в дальнейшем с тем, чтобы прописать нашу основную ноду, дабы новые ноды могли ее видеть и с ней синхронизироваться.

@mparkhomenko  По-моему, в Bitshares прям в исходниках каждой версии есть список узлов сети (в т.ч. ceed nodes), к которым будет пытаться подключаться твоя нода, не?

**Comment by ghost** [comment]
@kkrupovich 
Да, чтото подобное я там видел в сорсах, нужно с этим будет детальнее разобраться, а пока каждый наш инстанс это свой приватный тестнет, даже если тот же chain_id.

**Comment by cptn-solo** [comment]
BLOCK #22564195
TRANSFER |  
From | utd-core
To | map-13
Quantity | 300.00000 UTDEV
Спасибо!
