### ISSUE TITLE
Развертывание узла u-transnet

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#19]
Потренироваться можно и на старом дроплете, потом перенести на новый. 
Но тут вопрос во-первых, чего будет стоить переезд, и во вторых - есть ли что-то в конфигурации ноды, что привязывает ее к определенному адресу?

**Comment by ghost** [comment]
@kkrupovich 
[Genesis на базе BitShares со своим базовым активом](https://github.com/u-transnet/codebase/wiki/Genesis-%D0%BD%D0%B0-%D0%B1%D0%B0%D0%B7%D0%B5-BitShares-%D1%81%D0%BE-%D1%81%D0%B2%D0%BE%D0%B8%D0%BC-%D0%B1%D0%B0%D0%B7%D0%BE%D0%B2%D1%8B%D0%BC-%D0%B0%D0%BA%D1%82%D0%B8%D0%B2%D0%BE%D0%BC)
Сам узел бегает на втором дроплете [transnet.space](http://transnet.space/)
