### ISSUE TITLE
Интеграция faucet

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#20]
По результатам #16 д.б. понятно - нужен ли фасет, и если нужен - действуем. 
UP: Фасет нужен, действуем. 

(В итоге мы должны получить обе ноды (Bitshares + u-transnet) с фасетами и шлюзами друг на друга)

**Comment by DmitryUspensky** [comment]
@kkrupovich, реализована интеграция с фасетом для Bitshares, ты слишком много запихнул в эту задачу, например для создания шлюза есть своя задача, поэтому закрываем.

**Comment by cptn-solo** [comment]
@UspenskyDritry я просто думал, что это задача только под интеграцию фасета в новый инстанс (u-transnet) - может оставим пока открытой задачу эту? Посмотрел в проекте - вроде другой (для u-transnet) такой нет.

**Comment by cptn-solo** [comment]
Номер блока принятия в работу #21783940 ( @mparkhomenko  300 скилла, в работе до 15 ноября)

**Comment by ghost** [comment]
Правка зависимостей под более простой деплой
Номер блока увеличения трудозатрат #22015928 (@mparkhomenko +150 скилла, в работе до 25 ноября)

**Comment by ghost** [comment]
@kkrupovich
Фасет развернут и работает, принимает _POST_:
[Transnet Faucet](https://transnet.space:10443/api/v1/accounts)
Подергать можно при помощи [доки](https://github.com/u-transnet/codebase/wiki/%D0%A0%D0%B0%D0%B7%D0%B2%D0%B5%D1%80%D1%82%D0%BA%D0%B0-%D0%B8-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-faucet-%22tapin%22)
[Поправлены зависимости](https://github.com/u-transnet/utransnet-faucet/commit/e4acf048bfd194df58a399b2532425dbf73ba2d0)
[Добавлена наша сеть и зависимости](https://github.com/u-transnet/python-utransnet/commit/ededc4d9eef264d951367b0c72328ef2a7bdca6d)
[Добавлен префикс](https://github.com/u-transnet/python-graphenelib/commit/b9f7b3fc094067b9b5a14af24afb64486986d028)

**Comment by cptn-solo** [comment]
BLOCK #22074516 map-13 450.00000 UTDEV спс
