### ISSUE TITLE
Функция регистрации под U-TECH

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#21]
Необходимо развернуть фасет (tapin), к которому бы подключалась наша точка входа в блокчейн Bitshares и снабдить нашу точку входа формой регистрации нового пользователя по модели Учетная запись

**Comment by cptn-solo** [comment]
Требования функции регистрации важно адаптировать под реферальную модель (ТЗ формируется в #23) - например, важно предусмотреть возможность указания реферала - как в ссылке, так и в отдельном поле на форме регистрации, см. фасет xeroc на [bitshares.eu](https://bitshares.eu)

**Comment by cptn-solo** [comment]
@UspenskyDritry коллега, укажи плз ссылку на задачу, в рамках которой ты это делал и где описаны результаты, или если такой задачи нет - опиши результаты (со ссылками) здесь. Я так понимаю, саму функцию мы реализовали, т.ч. эту задачу можно закрывать. Дальнейшие доработки будем оформлять уже отдельными задачами

**Comment by DmitryUspensky** [comment]
@kkrupovich, реализовано в [задаче](https://github.com/u-transnet/codebase/issues/20). Нужно вылить на хостинг нашу морду. Что касается @mparkhomenko то тоже все сделано (фасет развернут, аккаунты регаются).
