### ISSUE TITLE
Развернуть GUI (референтный кошелек) под новую ноду

### ISSUE THREAD

**Issue by ghost** [u-transnet/codebase#25]
Развернуть GUI на ноде transnet, разрулить через nginx работу с faucet.
Должна быть нода с мордой и рабочим faucet.
Нужно задокументировать процесс, залить в git релевантные правки, если такие будут.

**Comment by ghost** [comment]
Номер блока принятия в работу #21815319 ( @mparkhomenko 300 скилла, в работе до 17 ноября)

**Comment by cptn-solo** [comment]
@mparkhomenko Я правильно понимаю, что задачу #20 мы закроем вместе с этой задачей и часы по #20 которые еще остались будут расходоваться параллельно с текущей задачей?

**Comment by ghost** [comment]
@kkrupovich да, faucet уже развернут, но я хочу всю документацию и изменения в коде подбить по результатам этих двух связанных задач.

**Comment by cptn-solo** [comment]
@mparkhomenko  Я к тому, что развернутый фасет толком не протестируешь, пока не подключишь к морде, вот в чем замес основной.

**Comment by ghost** [comment]
@kkrupovich протестировать можно любым rest клиентом + cli_wallet, он работает
Как выяснилось, нужно немного поправить исходники морды, нужна помощь @UspenskyDritry чтобы был наш префикс и была наша нода прописана из коробки, документацию сегодня выложу и готово сразу по этой и #20 задаче

**Comment by cptn-solo** [comment]
@mparkhomenko @UspenskyDritry что по срокам и скиллу? Если "просто не было времени" этим заняться - полагаю, дополнительный залог не нужен и это просто растянувшееся по времени мероприятие, которое изначально предполагалось завершить до конца пятницы. 

> Как выяснилось...

Если же вы готовы аргументированно увеличить трудозатраты - оценивайте сроки с учетом своей текущей загрузки и отписывайтесь сюда. В качестве аргументов готов рассмотреть результаты исследований, которые были проведены в процессе "как выяснилось"

**Comment by ghost** [comment]
@kkrupovich В исходниках морды зашит не над префикс (из-за этого регистрация не работает, наш фасет хочет наш префикс), так же в идеале нужно поправить адрес фасета и ноды, чтобы их руками в настройках на нашей морде не править. Так же раз уж их зашивать, нужно второй дроплет запарковать на домен, иначе придется айпишники голые указывать.
Я все запустил, но потребовались изменения, чтобы задачу можно было считать полноценно выполненной. Я не рассчитывал на внесение изменений в исходники морды.
Еще одна проблема если смотреть на будущее с целью простой развертки зоопарка, с которой пытаюсь разобраться я провозился в пятницу без успеха, это указать зависимости для нашего форка питонячей либы битшеерса, чтобы она юзала наш форк питонячего графена.
Нужен еще сегодняшний день, чтобы привести все в порядок.

**Comment by cptn-solo** [comment]
> В исходниках морды зашит не над префикс

Можешь напомнить - где это? ссылку на строку можно брать из брауза файла исходного кода.

> так же в идеале нужно поправить адрес фасета и ноды

Поддерживаю

> Так же раз уж их зашивать, нужно второй дроплет запарковать на домен

Второй или третий? у нас два домена, два дроплета, и оба домена запаркованы на дроплеты, если только @UspenskyDritry не запарковал оба домена на один дроплет

> указать зависимости для нашего форка питонячей либы битшеерса, чтобы она юзала наш форк питонячего графена

Поддерживаю. 

После ответов на вопросы предлагаю подумать об увеличении трудозатрат и объявить новый срок, чтобы мы ориентировали @alecvert - он стойкий солдат, но ему что-то нужно отвечать людям, чтобы нас не считали бездельниками и относились к нам серьезно.

**Comment by ghost** [comment]
@kkrupovich 
1) Если бы я знал где в исходном коде это прописано, сам бы уже поправил. Я пропробовал разобраться с этим, не смог, это будет отдельная задача для @UspenskyDritry.
2) Уже сделал сегодня в рамках овертайма.
3) Второй, по ходу оба домена запаркованы на 1й дроплет. Нужно разбираться с @UspenskyDritry, может он не так что-то понял.
4) Сегодня не успеваю уже с этим пунктом, придется завтра повозиться, дока тоже размазывается на два дня (сегодня-завтра) так-как она отчасти зависит от 4го пункта.

Сегодня я занимался данной задачей, понадобится еще завтрашний день, чтобы все закончить. Как итог на сегодня: фасет и морда запаркованы, рулятся через nginx, в морде наша нода и наш фасет указаны. Из упущений: не допилена дока, наши форки не указаны в зависимостях (это усложняет процесс развертки в будущем, приходится руками ставить из наших репов), морда не будет нормально дружить с фасетом изза префикса в ключах (отдельная задача для @UspenskyDritry, данную она не аффектит, ибо GUI будет считаться развернутым).

@UspenskyDritry  я сделал [ветку](https://github.com/u-transnet/utransnet-ui/tree/utt_nodes), где я поправил списки, можно в ней же будет поработать с префиксом. В будущем понадобится искать, что не работает с нашей нодой и править либо выпиливать такой функционал.

**Comment by cptn-solo** [comment]
@mparkhomenko @UspenskyDritry принимаем решение:
1. текущую задачу закрываем как выполненную после обновления документации;
2. добавляем скилл в задачу #20 для фиксов по регистрации/авторизации (фасет);
3. создаем отдельную задачу под адаптацию морды под работу с новым кодом базового аткива; адаптация под новый БА должна быть сосредоточена в 1ю очередь на модулях DPOS (голосование, права доступа, воркеры, etc.);

**Comment by ghost** [comment]
@kkrupovich 
[transnet.space](http://transnet.space/)
[Развертка референтного кошелька (GUI)](https://github.com/u-transnet/codebase/wiki/%D0%A0%D0%B0%D0%B7%D0%B2%D0%B5%D1%80%D1%82%D0%BA%D0%B0-%D1%80%D0%B5%D1%84%D0%B5%D1%80%D0%B5%D0%BD%D1%82%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BA%D0%BE%D1%88%D0%B5%D0%BB%D1%8C%D0%BA%D0%B0-(GUI))

**Comment by cptn-solo** [comment]
BLOCK #21994046 map-13 300UTDEV, возмещение в полном объеме, огонь, спасибо!

**Comment by mparkhomenko** [comment]
@kkrupovich 
2) Скилл добавляем под решение проблемы с зависимостями про которую я говорил, а пункт №3 будет включать в себя правки морды в том числе и префиксы?
Или же пункт №3 это про все остальное а скилл добавляем на префиксы и на зависимости забиваем?
