### ISSUE TITLE
SPIKE: RPC интерфейс узла на wss и интеграция с GUI

### ISSUE THREAD

**Issue by ghost** [u-transnet/codebase#26]
1) Научиться конфигурировать RPC интерфейс узла на SSL (wss://).
2)  Научиться интегрировать его с GUI
3) Настроить узел с SSL на transnet.space узле

1 день
150 skill

**Comment by ghost** [comment]
Номер блока принятия в работу #22015956 ( @mparkhomenko 150 скилла, в работе до 23 ноября)

**Comment by ghost** [comment]
@kkrupovich 
Можно принимать
[WSS узел Bitshares](https://github.com/u-transnet/codebase/wiki/WSS-%D1%83%D0%B7%D0%B5%D0%BB-Bitshares)
В [настройках](https://transnet.space:10443/settings) смотри вкладку _Access_.

**Comment by cptn-solo** [comment]
BLOCK #22051876 map-13 150UTDEV Спасибо!
