### ISSUE TITLE
Адаптация морды под работу с новым префиксом

### ISSUE THREAD

**Issue by ghost** [u-transnet/codebase#27]
Регистрация пользователя, импорт и экспорт ключей,- все, что связано с публичными ключами.
Нужно убедиться, что морда дружит с фасетом и работает бекап/рестор аккаунта и авторизация по модели аккаунта.

**Comment by ghost** [comment]
Номер блока принятия в работу #22018016 (@mparkhomenko 450 скилла, в работе до 25 ноября)

**Comment by cptn-solo** [comment]
@mparkhomenko главное не забудь чего делал, т.к. мы с @alecvert сегодня придумали одну штуку, и из-за этого базовый актив будем называть по-другому. прийдется переливать генезис скоро. Но это тренировка типа. Норм. По нашей документации любой сможет поднять свой форк шар за полчаса ;)))

**Comment by cptn-solo** [comment]
@mparkhomenko на сколько я помню, мы с Женей Обуховым находили массив в питонячем ЕМНИП коде, где реально просто не было нашего префикса, и вот та ошибка про ненайденный бин 58 бла бла объект - это как раз из-за того, что фасет передавал префикс, которого не было в том массиве. И это ЕМНИП был как раз код в либе python-bitshares. Возможно, об этом есть упоминание в задаче, где я собирал всю переписку по интеграции фасета, которую собирал по всем чатам.
Возможно - прям [тут](https://github.com/u-transnet/codebase/issues/16#issuecomment-329728764)
Т.е. наш бранч либы - это где-то в [этом](https://github.com/u-transnet/python-utransnet/blob/40188154f07c6236fe610b44fdd05371ea748b55/bitsharesbase/chains.py#L3) районе

**Comment by ghost** [comment]
@kkrupovich я это уже давно сделал, проблема именно в том, что js отдает в python не наш преффикс, а python его не принимает, тк ждет UTT.

**Comment by cptn-solo** [comment]
Я просто не увидел в нашем бранче UTT

**Comment by ghost** [comment]
@kkrupovich запушил, теперь видно будет

**Comment by ghost** [comment]
@kkrupovich 
[Разобрался, где лежали префиксы](https://github.com/u-transnet/bitsharesjs-ws/commit/8472bdb302edfc564ec4509b7c42739b74cd8f37)
[Пробуй регаться](https://transnet.space:10443/)
Сделал еще в субботу, потом мучался с зависимостями. Так и не смог нормально настроить зависимости, в итоге руками подсунул наши. Нужна будет задача на JS боженьку, чтобы тот организовал через зависимости наш fork.
На счет бекапа и рестора, в новой морде оставили только логин/пароль. Не актуально стало для новых пользователей, а старых у нас и нет пока что.

**Comment by cptn-solo** [comment]
> На счет бекапа и рестора, в новой морде оставили только логин/пароль. Не актуально стало для новых пользователей, а старых у нас и нет пока что.

Нет. через advanced mode норм бэкапится и ресторится кошелек. Я зарегал cptn-solo по модели кошелек в Chrome, экспортнул бин-файл и импортнул в Firefox.
Насчет JS не понял, возможно, имеет смысл обсудить задачу с @EvgeniyPolyakov (сформулировать и зафиксировать, не обязательно сразу делать)

**Comment by ghost** [comment]
@kkrupovich @EvgeniyPolyakov https://github.com/u-transnet/transnet.space/issues/5

**Comment by cptn-solo** [comment]
@EvgeniyPolyakov это на будущее задача, просто ребзя сами не справятся, там нужен скилл JS разработчика. Возможно, ты сможешь помочь.

**Comment by EvgeniyPolyakov** [comment]
@kkrupovich хорошо

**Comment by cptn-solo** [comment]
BLOCK #22166090
TRANSFER |  
From | utd-core
To | map-13
Quantity | 450.00000 UTDEV

Спасибо.
