### ISSUE TITLE
Адаптировать наш Docker и compose от битшары под наш faucet и ui

### ISSUE THREAD

**Issue by ghost** [u-transnet/codebase#28]
Faucet, ui и нода на transnet.space должен заработать через Docker, задокументировать процесс.

**Comment by cptn-solo** [comment]
@mparkhomenko 
Просьба рассмотреть [опыт коллег](https://github.com/u-transnet/codebase/issues/16#issuecomment-342123917)
Обсудили 1 день, т.ч. можешь скиловать

**Comment by ghost** [comment]
BLOCK #23567996
map-13
150UTDEV.SKILL
до утра 17.01.2018

**Comment by cptn-solo** [comment]
@mparkhomenko когда удастся заняться?

**Comment by ghost** [comment]
В процессе появилась ясность в создании еще докера под nginx который будет рулить всем добром, в случае с bitshares допустимо оставлять его за рамками докера, но тут мы должны будем давать легкий способ поднять все все все нужное и рабочее буквально 1 команду.
Еще день влетел из-за болезни.
Переносится на обед 24.01.18.

BLOCK #23800950
map-13
+300UTDEV.SKILL
до обеда 24.01.18

total 450UTDEV.SKILL

**Comment by ghost** [comment]
@kkrupovich 
Что было сделано:
Адаптация dockerfiles и docker-compose [тут](https://github.com/u-transnet/dockerfiles/pull/4)
Обработка SIGTERM в скриптах заверителей [тут](https://github.com/u-transnet/witness-scripts/pull/4)
Разбор полетов с нашей зависимостью graphene для python изза проблем с фасетом [тут](https://github.com/u-transnet/python-graphenelib/releases/tag/0.5.4-utt)
Адаптация конфига фасета и апстрим от рудекса [тут](https://github.com/u-transnet/utransnet-faucet/pull/2) и [тут](https://github.com/u-transnet/utransnet-faucet/pull/3)
Апстрим фасета рудекса в наш фасет для битшары [тут](https://github.com/u-tech-bitshares/faucet/pull/3)

После `docker-compose up` морда доступна на http://localhost, нода ws://localhost/ws, faucet на http://localhost
Еще нужен день чтобы аккуратно поднять через него все на нашем домене через https, развести nginx сайта от зоопарка ноды и при этом как то не посеять данные ноды
Данную задачу можно закрывать, под миграцию создаю [новую задачу](https://github.com/u-transnet/codebase/issues/50) и ухожу на день на нее

**Comment by cptn-solo** [comment]
@mparkhomenko 

BLOCK #23856362

TRANSFER |  
-- | --
From | utd-core
To | map-13
Quantity | 450.00000 UTDEV

Круто. @mparkhomenko надо начать писать readme  для желающего поднять ноду - что-то вроде руководства для домохозяйки. Готов помочь. И это довольно приоритетно.

**Comment by ghost** [comment]
На выходе #50 и #51 задачи, эту тогда закрываю.
