### ISSUE TITLE
Развернуть GUI через Docker, указав наши faucet и узел

### ISSUE THREAD

**Issue by ghost** [u-transnet/codebase#30]
Прописать наш faucet и наш узел в форке GUI (bitshares-ui)
Разобраться с Docker
Развернуть наш форк GUI через Docker на transnet.tech
Задокументировать

**Comment by ghost** [comment]
BLOCK #22193155
map-13
300 UTDEV.SKILL
До вечера 29.11.2017

**Comment by ghost** [comment]
@kkrupovich 
Прописал [изменения](https://github.com/u-tech-bitshares/bitshares-ui/commit/03b36217391ef9f1ac7e00c41aeb27cae667a4ec)
Развернутый [кошелек](https://transnet.tech:10443/)
[Dockerfile](https://github.com/u-tech-bitshares/dockerfiles/blob/master/bitshares-ui/Dockerfile) доступен в репозитории
Доработал [статью](https://github.com/u-transnet/codebase/wiki/%D0%A0%D0%B0%D0%B7%D0%B2%D0%B5%D1%80%D1%82%D0%BA%D0%B0-%D1%80%D0%B5%D1%84%D0%B5%D1%80%D0%B5%D0%BD%D1%82%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BA%D0%BE%D1%88%D0%B5%D0%BB%D1%8C%D0%BA%D0%B0-(GUI)), раздел _Развертка через Docker_

**Comment by cptn-solo** [comment]
BLOCK #22384825
TRANSFER |  
From | utd-core
To | map-13
Quantity | 300.00000 UTDEV
Спасибо!
ЗЫ: @mparkhomenko эта транзакция ушла в сеть через морду, поднятую на моей машине ;)
