### ISSUE TITLE
SPIKE: проанализировать требования протокола Lightning network

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#31]
сформулировать требования к [новому] типу объектов блокчейна и [новому] плагину для обработки объектов данного типа для обеспечения возможности реализации atomic swap

**Comment by cptn-solo** [comment]
@UspenskyDritry заскилуй плз на 29 ноября 2017, как договаривались

**Comment by DmitryUspensky** [comment]
BLOCK [#22217593](https://wallet.bitshares.eu/block/22217593) uspenskydmitry1970 250UTDEV.SKILL до вечера 30 ноября 2017

**Comment by DmitryUspensky** [comment]
Полезная [ссылка](https://bitnovosti.com/2016/06/22/understanding-the-lightning-network/) про работу Lightning Network, оставлю тут.

**Comment by cptn-solo** [comment]
@UspenskyDritry все-таки было бы неплохо попытаться сформулировать какой-то сухой остаток по этим исследованиям. 
Будем ли мы развивать эту идею или мы просто закопались в проблему, ничего не поняли и забросили как несвоевременную/безнадежную/неэффективную - какую?

**Comment by DmitryUspensky** [comment]
[Lightning network](https://lightning.network/) это грубо говоря надстройка над сетью. Изначально она создавалась как ускорение для сети Bitcoin. Т.е. между участниками сделки создается канал в соответствии с протоколом. После того как все участники сделки будут удовлетворены и каждый участник достигнет своей цели канал закрывается и конечные транзакции пушатся в сеть. Lightning network необходимо реализовать в ядре графена насколько я понимаю. Это трудозатратно, предлагаю втащить к нам после того как сообщество запилит что-то похожее или реализует Lightning network.

**Comment by cptn-solo** [comment]
@UspenskyDritry в общем я лично пока понял лишь то, что биткойн - это биткойн, а графен (BTS, UTT, etc.) - это графен. И все, к чему мы можем стремиться, это научиться передавать биткойн между учетками/участниками графена, имеющими соответствующие счета в сети биткойн, фиксируя этапы сделки между этими участниками в цепи графена в транзакциях определенного (нового) типа. 
цепь биткойна: А -> bitcoin -> B
цепь графена: B' -> UTT -> A'
Обе транзакции инициируются из графена и контролируются им. Как это сделать - предмет отдельного исследования. Так?

**Comment by DmitryUspensky** [comment]
Получается так:
В Bitcoin и Litecoin Lightning network реализована. Если участники хотят обменяться активами они создают канал, проводят сделки, при этом токены в обоих сетях блокируются временными блокировками, после канал закрывается и результаты пушатся в сети. В graphene же нет реализации Lightning network, нет возможности создать канал, блокировать средства так чтобы об этом знала другая сеть. Т.е. Lightning network канал это как временный мостик, а блокчейны это острова. Люди кидают мостики между островами, выходят с доверенностями на токены, которые заблокированы для трат на время переговоров. После того как люди договоряться на мостике, они пожимают руки и подписывают договора, которые законны на обоих островах. Несут договора обратно на острова разблокируют средства и они сами по мосту переходят между островами и мост уничтожается. Но для того чтобы мост (канал) пристыковать на остров нужно чтобы берег острова был Lightning network и сундуки на острове могли блокировать часть своих монет на время переговоров. 
В graphene пока нет реализации. Нужно допиливать graphene core. Они умные ребята интересно что придумают.

**Comment by cptn-solo** [comment]
@UspenskyDritry но тем не менее - основное - это все же условная передача средств внутри графена, при этом условием является передача средств в другом блокчейне. Таким образом (безотносительно lightning network) не обязательно обе цепи модифицировать. Достаточно модифицировать графен, научить его блокировать средства на время или под условие осуществления транзакции во внешней цепи. 
То есть, если, например, биткойн взять за второстепенную цепь, и инициировать первой транзакцию в графене между B и A, то у нее может быть либо успешное завершение, либо возврат средств B, а условием успешного завершения может быть, например, фиксирующиеся в транзакции графена адреса биткойн-цепи (откуда и куда) и сумма, которая туда должна попасть для разблокировки средств и завершения сделки. Если эти условия не случаются в течение заданного промежутка времени - транзакция в графене откатывается (не подтверждается). 
(Проблема тут скорее в том, что делать при возникновении сбоев. )
 
1. графен: B [->] A (предложение транзакции, указание адресов биткойн-цепи, суммы, блокировка средств на время t)
2. биткойн: A -> B (отправка средств, получение идентификатора транзакции);
3. графен: получение идентификатора транзакции биткойн и идентификация предложения транзакции из п.п.1 (по концам транзакции);
4. графен: мониторинг транзакции, продление блокировки вплоть до получения необходимого количества подтверждений в цепи биткойн);
5. графен: после получения подтверждения транзакции биктойн-цепи - завершение п.п.1 
6. графен: если транзакция в биткойне не финализирована - средства должны зависнуть и в графене. 

Кроме того, анализ транзакции в биткойн-сети возможен и без ноды биткойна - достаточно реализовать алгоритм, схожий с подачей котировок заверителями для подачи статуса транзакций в цепи биткойна - как только получено подтверждение от определенного количества заверителей о финальном состоянии транзакции в биткойне - транзакция в графене может считаться так же финализированной;

**Comment by DmitryUspensky** [comment]
Научить блокировать средства под условие осуществления транзакции во внешней цепи это ключевое во всем. Как научить именно graphene, а не свой шлюз понимать что происходит в другой сети. Средства блокировать думаю не сильно проблема можно придумать. Можно мутить тему где будет 3-я сторона которая будет знать что твориться в graphene и в bitcoin. Но это 3-я сторона а на p2p. По сути lightning network это зашитая в ядра bitcoin и litecoin третья сторона, но которая уже часть ядер.

**Comment by cptn-solo** [comment]
@UspenskyDritry как мониторить состояние транзакции мы знаем - это либо нода этого блокчейна рядом с нодой заверителя, либо использование API этого блокчейна. Ключевое отличие от p2p и третьей сторны "в блокчейне" у графена в том, что у него есть заверители. Если мы им верим в вопросе курсов внешних валют (котировок) - то почему не можем/не должны верить в вопросе статуса транзакций во внешних цепях?

**Comment by cptn-solo** [comment]
В общем, предлагаю считать эту дискуссию плодотворной и продолжать развивать конкретно направление делегирования проверки внешних транзакций заверителям: #40

**Comment by cptn-solo** [comment]
BLOCK #22465172
TRANSFER |  
From | utd-front
To | uspenskydmitry1970
Quantity | 250.00000 UTDEV
Спасибо!
