### ISSUE TITLE
Поднять faucet на transnet.space через Docker

### ISSUE THREAD

**Issue by ghost** [u-transnet/codebase#32]
Развернуть faucetI через Docker на transnet.tech
Задокументировать

**Comment by ghost** [comment]
BLOCK #22246705
map-13
150 UTDEV.SKILL
До вечера 30.11.2017

**Comment by ghost** [comment]
@kkrupovich 
Прописал [изменения](https://github.com/u-tech-bitshares/faucet/commit/22ec656ad7717795ac6614b96af2324770907ed5)
Развернутый [faucet](https://transnet.tech:10443/api/v1/accounts) смотрит на testnet, нужнен акк и его active key для переключения на prod
[Dockerfile](https://github.com/u-tech-bitshares/dockerfiles/blob/master/faucet/Dockerfile) доступен в репозитории
Доработал [статью](https://github.com/u-transnet/codebase/wiki/%D0%A0%D0%B0%D0%B7%D0%B2%D0%B5%D1%80%D1%82%D0%BA%D0%B0-%D0%B8-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-faucet-%22tapin%22), раздел _Развертка через Docker_

**Comment by cptn-solo** [comment]
BLOCK #22332981
TRANSFER |  
From | utd-core
To | map-13
Quantity | 150.00000 UTDEV
Спасибо!
