### ISSUE TITLE
Сделать актуальный config для faucet

### ISSUE THREAD

**Issue by ghost** [u-transnet/codebase#37]
Сделать актуальный config для faucet для регистрации на prod сети BTS.

**Comment by ghost** [comment]
@kkrupovich
BLOCK #22412721
map-13
150 UTDEV.SKILL
До вечера 05.12.2017

**Comment by ghost** [comment]
@kkrupovich
Доступно [тут](https://transnet.tech:10443/)
[Задача](https://github.com/u-transnet/codebase/projects/1#card-6028168) на будущее

**Comment by cptn-solo** [comment]
BLOCK #22419067
TRANSFER |  
From | utd-core
To | map-13
Quantity | 150.00000 UTDEV

Спасибо!
