### ISSUE TITLE
Использовать Docker Compose

### ISSUE THREAD

**Issue by ghost** [u-transnet/codebase#38]
Использовать [Docker Compose](https://docs.docker.com/compose/) для легкого деплоя node + faucet + GUI

**Comment by ghost** [comment]
BLOCK #22551471
map-13
150UTDEV.SKILL
до вечера 11.12.2017

**Comment by ghost** [comment]
Переносится на 12.12.2017 из-за [приоритетной задачи](https://github.com/u-transnet/codebase/issues/41)

**Comment by cptn-solo** [comment]
@mparkhomenko ты же этой задачей закрываешь потребность в инструменте для компоновки контейнеров? т.е. докер "ноды заверителя" можно будет соорудить как-то проще/правильнее?

**Comment by ghost** [comment]
@kkrupovich да, все верно

**Comment by ghost** [comment]
BLOCK #23744479
map-13
+150UTDEV.SKILL
до утра 22.01.2018

Потребовалось больше времени на задачу
Total 300UTDEV.SKILL

**Comment by ghost** [comment]
@kkrupovich 
Докер для битшары немного устарел, пришлось [поправить](https://github.com/u-tech-bitshares/dockerfiles/commit/ea4baeecac5dd1b6333abed707acbd661d8dba48).
В [документации](https://github.com/u-transnet/codebase/wiki/%D0%A0%D0%B0%D0%B7%D0%B2%D0%B5%D1%80%D1%82%D0%BA%D0%B0-witness-node-BitShares-%D0%B8-CLI-Wallet-%D0%BD%D0%B0-linux-%D0%BC%D0%B0%D1%88%D0%B8%D0%BD%D0%B5-%D0%B8%D0%B7-%D0%B8%D1%81%D1%85%D0%BE%D0%B4%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2) тоже обновил.
Понадобилось еще вот [это](https://github.com/u-tech-bitshares/dockerfiles/commit/7e4c324b97798d28545921a992134d08c518b1bf) для эффективности при перезапуске.
Докер от кошелька тоже устарел, [исправил](https://github.com/u-tech-bitshares/dockerfiles/commit/47c7022cef71bbd97ee052a826e5635a518af362).
[Compose файл](https://github.com/u-tech-bitshares/dockerfiles/commit/59059d9392a7e79c0f3e9c5e4acfc8b660b237ff) обкатан, на нем сейчас наш [tech домен](https://transnet.tech:10443).
Все закрыто от внешней сети, доступ разруливается через nginx хост машины. Для нашего докера уже потребуется nginx в рамках контейнера.
Много убил времени, на попытки перетащить volume от старого контейнера с нодой.
Накопленный опыт полезен для [задачи](https://github.com/u-transnet/codebase/issues/28).

**Comment by cptn-solo** [comment]
BLOCK #23857646

TRANSFER |  
-- | --
From | utd-core
To | map-13
Quantity | 300.00000 UTDEV
