### ISSUE TITLE
Реализация контракта распределения токена согласно алгоритму, выработанному и зафиксированному ранее

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#4]
На данный момент эта задача служит точкой входа для исследований и документирования процедур выпуска токена на эфире, а так же в целом - связывать техническую реализацию процедуры распределения токена с концепцией, фиксируемой в рамках [другой](/u-transnet/info/issues/2) задачи 
TBD: добавить @UspenskyDritry, он вроде у нас по эфиру первый после @plshapkin . Или наоборот?

**Comment by cptn-solo** [comment]
@UspenskyDritry @plshapkin 
Парни, надо оценить возможность выпуска ERC20 и запуска распределения тнанзитного актива (UIA UTECH.UTCORE, предполагаемый к выкупу за реальный инфраструктурный MPA актив UTCORE) по модели, [предложенной](https://golos.io/ru--blokcheijn/@blockchained/logicheski-posledovatelnye-principy-raspredeleniya-tokena-eos) Ларимером.
Есть [репозиторий](https://github.com/EOSIO/eos-token-distribution), в котором выложен в т.ч. контракт. 

@alecvert если можешь что-то добавить - welcome.

И предлагаю объявить тендер на реализацию прототипа решения:
1. ERC20 - анализ, адаптация, выпуск на тестнете (если он вообще есть в эфире, должен быть по идее);
2. прототип веб-морды для внесения эфира и отправки токена на указанный покупателем адрес;
3. прототип веб-морды для востребования UTECH.UTCORE (есть [докер](https://github.com/u-transnet/codebase/wiki/Развертка-witness-node-BitShares-и-CLI-Wallet-на-linux-машине-из-исходников), который @mparkhomenko модифицирует под ноду u-transnet, и которую можно будет использовать для отладки функционала);

**Comment by alecvert** [comment]
@kkrupovich заклеймить ERC20 надо еще. Или ты это уже написал?

прототип веб-морды для внесения эфира и отправки токена на указанный покупателем адрес;- не только eth, но и btc, lightcoin и лругих топовых крипт, которые  в обиходе

**Comment by cptn-solo** [comment]
@alecvert востребование = "заклэймить", мы ж русские люди

**Comment by cptn-solo** [comment]
Из чата с @UspenskyDritry 
я пока одно только не понимаю. куда именно сохраняется публичник, который ты регаешь в процессе распределения.
1. сначала клэймится ERC20 в обмен на эфир, пропорционально твоей доле в окне. Клэймится после закрытия этого окна.
2. где-то тут можно прилепить свой публичник U-TRANSNET куда-то в контракт, видимо, если это есть в протоколе ERC20
3. заходишь в морду U-TRANSNET, выбираешь "Клэйм UTCORE" в меню и скармливаешь адрес своего эфирного кошелька - тебе выпускается UTECH.UTCORE, и можешь с ним делать все, что доступно в нашем дэксе, либо выводишь в Bitshares, например

**Comment by cptn-solo** [comment]
Начинаем с подробного анализа и проверки наших предположений в спайке #41 
Потом возвращаемся к задаче уже с точки зрения практической реализации - создаем репозиторий, проект и конкретные задачи на разработку @UspenskyDritry @mparkhomenko просьба заскиловать #41 и все аккуратно проверить

**Comment by cptn-solo** [comment]
@alecvert @LastWarrior чтобы вы был вкурсе:
Добавили спайк на альтернативную схему распределения - бот-аукционер #42 - т.к. эту схему обязательно надо рассмотреть в свете выработки итоговой процедуры распределения в рамках [основной задачи](https://github.com/u-transnet/info/issues/2)
