### ISSUE TITLE
SPIKE: Анализ и документирование процедуры распределения и востребования (клэйма) токена направления с использованием ERC20

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#41]
Необходимо аккуратно задокументировать процедуру регистрации публичных и приватных ключей в блокчейнах u-transnet / ethereum для последующей реализации схемы в проектах новых инфраструктурных направлений transnet space. Первоначальная постановка задачи в #4 
Результаты исследований фиксируем в wiki репозитория codebase

**Comment by cptn-solo** [comment]
@UspenskyDritry @mparkhomenko парни, Желательно уже в процессе работы получить репозиторий и доску проекта в нем с раскладкой работ по направлениям. Задачи создавать не надо - вместе создадим после того, как картина прояснится.

**Comment by DmitryUspensky** [comment]
BLOCK [#22557191](https://wallet.bitshares.eu/block/22557191) uspenskydmitry1970 125UTDEV.SKILL до вечера 11 декабря 2017

**Comment by ghost** [comment]
BLOCK #22557283 map-13 150UTDEV.SKILL до вечера 11 декабря 2017

**Comment by cptn-solo** [comment]
@UspenskyDritry схему в бранч текущего репозитория и ссылку на открытие через draw.io результирующим комментом сюда плз.

**Comment by DmitryUspensky** [comment]
@kkrupovich, проверяй [диаграмма](https://www.draw.io/#Hu-transnet%2Fcodebase%2Ferc20%2FICO_sheme.xml).

**Comment by cptn-solo** [comment]
@UspenskyDritry диаграмму вижу. 
- Обзови только не Архитектурой, а Процедурой распределения, и не ICO - это TDE (token distribution event) или что-то вроде
- Но надо добавь туда архитектуру решения - первой страницей на этом листе, либо новый лист добавить - и там перечислить компоненты нашей информационной системы, задействованные в процедуре (АПИ, сайт, ключи в клиенте, БЧ U-TRANSNET, БЧ ETHEREUM, протоколы взаимодействия - wss, json, etc. )
- ИМХО нужна схема возврата средств еще

**Comment by DmitryUspensky** [comment]
BLOCK #[22557191](https://wallet.bitshares.eu/block/22614061) uspenskydmitry1970 250UTDEV.SKILL до вечера 12 декабря 2017

**Comment by DmitryUspensky** [comment]
@kkrupovich, [поправил](https://www.draw.io/#Hu-transnet%2Fcodebase%2Ferc20%2Ferc20%2FTDE_sheme.xml)

**Comment by cptn-solo** [comment]
BLOCK #22617237
TRANSFER |  
From | utd-front
To | uspenskydmitry1970
Quantity | 375.00000 UTDEV

BLOCK #22617317
TRANSFER |  
From | utd-core
To | map-13
Quantity | 150.00000 UTDEV

Спасибо, парни, погнали дальше в #43
