### ISSUE TITLE
SPIKE: Анализ и документирование процедуры распределения токена направления с использованием бота-аукционера

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#42]
Допустим есть учетка размещения - ей рулит бот. На учетку стейкхолдеры трансферят напечатанный токен направления (бот видит историю транз и подразумевается, что результаты продажи окна будут распределены пропорционально по всем участникам)
Допустим, окно началось, продали 1000 токенов (размер окна), получили 452 эфирки/тугрика.
После закрытия окна 452 эфирки/тугрика бот раскидывает обратными транзакциями стейкхолдерам, принявшим участие в окне.
Пропорционально тому кто сколько % закинул в эту 1000
И так далее.
Пуля в пулю с ERС20, только все ппц как замотивированы на участие :)

**Comment by cptn-solo** [comment]
@mparkhomenko  схему в бранч текущего репозитория и ссылку на открытие через draw.io результирующим комментом сюда плз.

**Comment by ghost** [comment]
BLOCK #22591854 map-13 150UTDEV.SKILL до вечера 12 декабря 2017

**Comment by mparkhomenko** [comment]
[Репозиторий](https://github.com/u-transnet/codebase/tree/exchange_bot/Raising%20funds%20by%20exchange%20bot)

**Comment by ghost** [comment]
@kkrupovich 
[Схема](https://www.draw.io/?title=Raising%20funds%20by%20exchange%20bot.xml#Uhttps%3A%2F%2Fraw.githubusercontent.com%2Fu-transnet%2Fcodebase%2Fexchange_bot%2FRaising%2520funds%2520by%2520exchange%2520bot%2FRaising%2520funds%2520by%2520exchange%2520bot.xml)
[Репозиторий](https://github.com/u-transnet/codebase/tree/exchange_bot/Raising%20funds%20by%20exchange%20bot)

**Comment by cptn-solo** [comment]
Так. Схема конечно так себе, но процедуру расписал норм. Надо будет потом сделать диаграмму процесса по аналогии с [MPA-ECONOMY](https://www.draw.io/#Hu-transnet%2Finfo%2Fmaster%2Funity_concept.xml).M8, но это можно указать в #43 в одной из задач на проектирование

BLOCK #22615453
TRANSFER |  
From | utd-core
To | map-13
Quantity | 150.00000 UTDEV
Спасибо!
