### ISSUE TITLE
Проработка плана реализации компонентов схем распределения токена (ERC + Bot)

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#43]
На [доске проекта](https://github.com/u-transnet/codebase/projects/4?) собираем план работ для последующего выделения задач по реализации схем распределения, проанализированных в рамках спайков #41 (ERC20) и #42 (бот-аукционер).
Определяем смежные участки, расставляем приоритеты реализации. Выходим на понимание общей последовательности работ. 
@mparkhomenko, просьба проскиловать эту задачу на сегодня и завтра и будешь ответственным по проекту.

**Comment by cptn-solo** [comment]
@UspenskyDritry думаю, аналогично, все-таки если мы взялись спроектировать этот хлам - надо проектировать. Тебе предлагаю тоже полностью переключиться на эту задачу как минимум на сегодня и завтра.

**Comment by ghost** [comment]
BLOCK #22615775 map-13 300UTDEV.SKILL до вечера 14 декабря 2017

**Comment by DmitryUspensky** [comment]
BLOCK #[22617395](https://wallet.bitshares.eu/block/22617395) uspenskydmitry1970 125UTDEV.SKILL до вечера 14 декабря 2017

**Comment by ghost** [comment]
BLOCK #22674689 map-13 150UTDEV.SKILL до вечера 15 декабря 2017
14 декабря 2017 захворал, не успел все закончить в связи с этим

**Comment by DmitryUspensky** [comment]
@kkrupovich, [результат](https://www.draw.io/#Hu-transnet%2Fcodebase%2Ferc20%2Ferc20%2FTDE_sheme.xml).

**Comment by ghost** [comment]
@kkrupovich 
По шлюзу завершено, нужен созвон для актуализации видения.
По результатам данной задачи и созвона на сегодня нужно доработать [spike](https://github.com/u-transnet/codebase/projects/4#card-6224156)
Описание доступно в [репозитории](https://github.com/u-transnet/codebase/tree/gate/Gate%20UTT%20-%20ETH)
Обе схемы доступны [тут](https://www.draw.io/?lightbox=1&highlight=0000ff&layers=1&nav=1&title=Gate.xml#Uhttps%3A%2F%2Fraw.githubusercontent.com%2Fu-transnet%2Fcodebase%2Fgate%2FGate%2520UTT%2520-%2520ETH%2FGate.xml)

**Comment by cptn-solo** [comment]
@UspenskyDritry 
> @kkrupovich, результат.

BLOCK #22753952
TRANSFER |  
From | utd-front
To | uspenskydmitry1970
Quantity | 125.00000 UTDEV

Спасибо, уходим на след. итерацию #44

**Comment by cptn-solo** [comment]
@mparkhomenko 
> @kkrupovich
По шлюзу завершено, нужен созвон для актуализации видения.
По результатам данной задачи и созвона на сегодня нужно доработать spike
Описание доступно в репозитории
Обе схемы доступны тут

BLOCK #22756055
TRANSFER |  
From | utd-core
To | map-13
Quantity | 150.00000 UTDEV

Спасибо, уходим на след. итерацию #45

**Comment by cptn-solo** [comment]
BLOCK #22767351
TRANSFER |  
From | utd-core
To | map-13
Quantity | 300.00000 UTDEV
Хм. правда - закрыл только один транш. Теперь второй. Спасибо
