### ISSUE TITLE
Отдельно ERC20: Проработка плана реализации компонентов схем распределения токена

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#44]
Пришли из #43 

- добавляем в [схему](https://www.draw.io/#Hu-transnet%2Fcodebase%2Ferc20%2Ferc20%2FTDE_sheme.xml) отдельный токен ETH.UTCORE - см. в кач-ве референса мою [бизнес-схему](https://www.draw.io/#Hu-transnet%2Finfo%2Fmaster%2Fdrawings%2Fconcept-mpa-economy-m8-erc20.xml)
- форматируем листы по референсу (заголовок, примечания)
- убираем листы процедуры распределения и схемы возврата
- схему возврата пытаемся врезать в диаграму последовательности (низкий приоритет)

**Comment by cptn-solo** [comment]
смотрим сегодня вечером, скилл под 1 день.

**Comment by DmitryUspensky** [comment]
BLOCK #[22760777](https://wallet.bitshares.eu/block/22760777) uspenskydmitry1970 125UTDEV.SKILL до вечера 18 декабря 2017

**Comment by DmitryUspensky** [comment]
@kkrupovich,  [результат](https://github.com/u-transnet/codebase/blob/erc20/README.md)

**Comment by cptn-solo** [comment]
BLOCK #22768998
TRANSFER |  
From | utd-front
To | uspenskydmitry1970
Quantity | 125.00000 UTDEV

Смотрим #46
