### ISSUE TITLE
Отдельно Шлюз (ETH): Проработка плана реализации компонентов схем распределения токена

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#45]
Пришли из #43 

Продолжаем рисовать логику шлюза:

- проработка вопроса с memo в транзакции ETH
- проработка вопроса с "погашенными" транзакциями (сходимость)
- проработка логики децентрализованного подтверждения транзакции ETH при выводе
- проработка логики децентрализованного создания транзакции в графене

**Comment by cptn-solo** [comment]
1 день, до завтра 19 дек, созвон в первой половине дня

**Comment by ghost** [comment]
BLOCK #22756749 map-13 150UTDEV.SKILL до вечера 18 декабря 2017

**Comment by ghost** [comment]
@kkrupovich 
[Готово](https://github.com/u-transnet/codebase/tree/gate/Gate%20UTT%20-%20ETH)

**Comment by cptn-solo** [comment]
Посмотрел, в целом все норм, есть желание начать закрывать вопросы, а значит - развернуть инфраструктуру для создания/подписания/анализа транзакций в сети ETH.
Предлагаю озаботиться поиском информации об этом вам вдвоем с @UspenskyDritry  завтра

**Comment by cptn-solo** [comment]
BLOCK #22768935
TRANSFER |  
From | utd-core
To | map-13
Quantity | 150.00000 UTDEV

Смотрим #46
