### ISSUE TITLE
Выбор и развертывание API бч ETHEREUM. Сервер

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#46]
Выбрать и развернуть инструментарий для чтения/создания/подписывания транзакций в блокчейне ETH на стороне сервера. Предпочтительна реализация на Python. Разворачиваемся и отлаживаемся на узле u-transnet, подключаемся к тестнету ETH. 

Скоуп задач на исследование берем из результатов #45 

- При создании и подписывании - особое внимание мультиподписи, возможности замены ключей (в случае выхода из кольца одного из заверителей)
- При чтении - особое внимание на дешифровку мемо транзакции ETH в адрес шлюза

**Comment by cptn-solo** [comment]
@UspenskyDritry @mparkhomenko просьба заскиловать по дню на эту задачу и посмотреть завтра вместе что есть и что нам может подойти под задачи из #45

**Comment by DmitryUspensky** [comment]
BLOCK [22788848](https://wallet.bitshares.eu/block/22788848) 125UTDEV.SKILL до вечера 19 декабря 2017

**Comment by ghost** [comment]
BLOCK 22793890 150UTDEV.SKILL до вечера 19.12.2017

**Comment by cptn-solo** [comment]
Просьба зафиксировать результаты итерации, видимо, в ["готово"](https://github.com/u-transnet/codebase/tree/gate/Gate%20UTT%20-%20ETH) от @mparkhomenko , т.к. там наиболее развернутое описание планируемой реализации шлюза на данный момент. 
После этого закрываем итерацию и уходим на следующую ( #47 )

**Comment by ghost** [comment]
@kkrupovich 
[Зафиксировал](https://github.com/u-transnet/codebase/commit/a203b7f7881874d3d29f36e4b549b081b26609eb#diff-67e603b686ebcc1a1df5fd3f260aafd8)
[Поправил то, что ты просил](https://github.com/u-transnet/codebase/commit/b02a6016bc73bd666aa0e4517ca27d4cc164f7e5#diff-59690717e6eba7eaf3d108536e03fcbf)

**Comment by cptn-solo** [comment]
Закрываем. 
BLOCK #22822938
TRANSFER |  
From | utd-core
To | map-13
Quantity | 150.00000 UTDEV

BLOCK #22822971
TRANSFER |  
From | utd-front
To | uspenskydmitry1970
Quantity | 125.00000 UTDEV
