### ISSUE TITLE
Итерация №1 Выбор и развертывание API бч ETHEREUM. Сервер

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#47]
Пришли из #46 
Продолжаем: 
- развертывание и применение [API](https://github.com/ethereum/pyethapp/wiki/The_Console)
- исследуем выдачу ключа ETH под транзакцию депозита ([brainkey?](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki))
- исследуем мультиподпись - выдачу/отзыв ключей к кошельку ETH
- пробуем собрать работающий прототип на ноде transnet.space

**Comment by cptn-solo** [comment]
@UspenskyDritry @mparkhomenko просьба проскиловать на день, созвон завтра утром.

**Comment by ghost** [comment]
BLOCK 22809818 150UTDEV.SKILL до вечера 20.12.2017

**Comment by ghost** [comment]
@UspenskyDritry жду результатов из созвона в этой задаче

**Comment by DmitryUspensky** [comment]
BLOCK [22809879](https://wallet.bitshares.eu/block/22809879) 125UTDEV.SKILL до вечера 20 декабря 2017

**Comment by DmitryUspensky** [comment]
По результатам утреннего созвона, есть вопросы:
1. Проверить как генеряться ETH адреса с мультиподписью в морде Transnet. Смотреть на brain key.
2. Исследовать процесс получения RPC точки входа в Ethereum на примере Bitshares для входа в пиринговую сеть.
3. Создать ETH кошелек с мультиподписью. Попробовать в ручную поменять подписантов, эмулируя тем самым изменение списка делегатов.

**Comment by ghost** [comment]
**По адресам:**
1. [HD wallet в bitcoin](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki)
2. [brainkey стандарт](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki)

Нужно использовать HD Wallet в Ethereum. В поиске информации по реализации на python.

**По доступу:**
1. [RPC в Ethereum](https://github.com/ethereum/wiki/wiki/JSON-RPC)
2. [Python client](https://github.com/ethereum/pyethapp/wiki/The_Console)

**Comment by cptn-solo** [comment]
Резюме по созвону, и скилл на день до завтра. В обед созвон поставил.

**Comment by DmitryUspensky** [comment]
BLOCK  [22846730](https://wallet.bitshares.eu/block/22846730) 125UTDEV.SKILL до вечера 21 декабря 2017

**Comment by DmitryUspensky** [comment]
Мультиподписной кошелек (multisig) - это smart contract, который определяет требования к перемещению средств или взаимодействию с другими смарт-контрактами.
Набором ключей могут управлять один или несколько witnesses.
Таким образом необходимо написать ERC20 контракт с логикой мультиподписи. Подумать как / через что ERC20 будет общаться с Transnet witnesses.
Полезные ссылки:
https://github.com/paritytech/parity/wiki/Accounts,-Wallets,-Vaults

**Comment by ghost** [comment]
BLOCK 22847411 150UTDEV.SKILL до вечера 21.12.2017

**Comment by ghost** [comment]
### Проделано:
1. [Переход от адреса к секрету](https://github.com/u-transnet/codebase/commit/261fb22e8e52e72543b128df4862b59397978bd4)
2. Нашел неплохой [js hd wallet для Ethereum](https://www.npmjs.com/package/eth-hd-wallet), для Python не нашел ничего полезного (хотя искал долго и упорно), или самим придется реализовывать или же Node.js использовать.
### Продолжение:
1. Проверить как хранятся средства на HD кошельке в Ethereum и Bitcoin.
2. Уточнить может ли HDW быть мультиподписным.
3. Подумать может ли нам помочь smart контракт при вводе средств.
3. Создать задачу на подписывание эмиссии на python.
4. Python Listeners для просмотра транзакций в Ethereum. (**optional**)

**Comment by cptn-solo** [comment]
@mparkhomenko 
BLOCK #22873708
TRANSFER |  
From | utd-core
To | map-13
Quantity | 300.00000 UTDEV

@UspenskyDritry 
BLOCK #22873741
TRANSFER |  
From | utd-front
To | uspenskydmitry1970
Quantity | 250.00000 UTDEV

Спасибо, погнали дальше #48

**Comment by DmitryUspensky** [comment]
**Провелано**:
1. Найден прототип контракта мультиподписи.
2. Установлен Parity.

Продолжение:
1. Адаптация контракта под наши цели и создание тестового стенда в сети Ethereum.
