### ISSUE TITLE
Итерация №2 Выбор и развертывание API бч ETHEREUM. Сервер

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#48]
Пришли из #47 

Продолжаем 2 направления, 
1. Вход:
- создание адреса ETH для входящей транзакции (морда, HDW)
- создание транзы graphene
- - слушаем транзы ETH (сервер, скрипт заверителя)
- - подписывание graphene транз эмиссии (сервер, скрипт заверителя)

2. Выход:
- создание транзы в graphene (морда)
- создание транзы в ETH (сервер)
- подписывание транзы в ETH (сервер)
- - слушаем транзы ETH (сервер)
- сжигаем в graphene (сервер, скрипт заверителя)
- - подписывание graphene сжигания (сервер, скрипт заверителя)

Чего забыл?

**Comment by cptn-solo** [comment]
@UspenskyDritry @mparkhomenko скилуем два дня, смотрим понедельник вечером.

**Comment by ghost** [comment]
BLOCK 22870879 300UTDEV.SKILL до вечера 25.12.2017

**Comment by DmitryUspensky** [comment]
BLOCK [22873358](https://wallet.bitshares.eu/block/22873358), [22873400](https://wallet.bitshares.eu/block/22873400) 250UTDEV.SKILL до вечера 25.12.2017

**Comment by ghost** [comment]
1. Проверить как хранятся средства на HD кошельке в Ethereum и Bitcoin.
2. Уточнить может ли HDW быть мультиподписным.
3. ~~Создать задачу на подписывание эмиссии на python.~~
4. ~~Python Listeners для просмотра транзакций в Ethereum. (**optional**)~~

**Comment by ghost** [comment]
[Доска по шлюзу Ethereum](https://github.com/u-transnet/Gateway/projects/2)

**Comment by cptn-solo** [comment]
@mparkhomenko [карточка](https://github.com/u-transnet/Gateway/projects/2#card-6351319) про тестнет - не знаю, пообщался ты с @UspenskyDritry в итоге или нет - но идея была такая - нам нужен докер ноды u-transnet, дев-версия, полагаю, т.к. на нем мы будем поднимать скрипты listener, burner и проч. обвязку кольцевого шлюза. Либо можно упаковать скрипты кольцевого шлюза в отдельный докер, на манер faucet - главное чтобы можно было легко обновлять код на машинах заверителей и прогонять тесты в процессе исследований и отладки

**Comment by ghost** [comment]
BLOCK 23067074 +150UTDEV.SKILL до созвона утром 29.12.2017

**Comment by ghost** [comment]
@kkrupovich 
[Наша seed node](https://github.com/u-transnet/utransnet-core/commit/bdde103283d76b156c265fb515fc285baca3a20c)
[Docker](https://github.com/u-transnet/dockerfiles/tree/master/utransnet-core)
[Мануал](https://github.com/u-transnet/codebase/wiki/%D0%A0%D0%B0%D0%B7%D0%B2%D0%B5%D1%80%D1%82%D0%BA%D0%B0-witness-node-BitShares-%D0%B8-CLI-Wallet-%D0%BD%D0%B0-linux-%D0%BC%D0%B0%D1%88%D0%B8%D0%BD%D0%B5-%D0%B8%D0%B7-%D0%B8%D1%81%D1%85%D0%BE%D0%B4%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2#%D0%A0%D0%B0%D0%B7%D0%B2%D0%B5%D1%80%D1%82%D0%BA%D0%B0-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-docker)
[Поднял альтернативой не https морду для возможности использования localhost](http://transnet.space:10080/)

**Comment by cptn-solo** [comment]
@mparkhomenko 
BLOCK #23076932
TRANSFER |  
From | utd-core
To | map-13
Quantity | 450.00000 UTDEV
Спасибо!

@UspenskyDritry 
BLOCK #23077036
TRANSFER |  
From | utd-front
To | uspenskydmitry1970
Quantity | 750.00000 UTDEV
Спасибо! Но 500 из 750 - лишние и отправлены по ошибке - т.ч. либо это аванс под оставшийся скилл, либо верни при случае на utd-front

Уходим в доработку ноды под развитие скриптовой функциональности заверителей: [задача про докер со скриптами](https://github.com/u-transnet/Gateway/issues/6)
