### ISSUE TITLE
Автоматизировать и упростить работу со скиллом для подрядчиков:

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#49]
Предлагаю запилить телеграм-бота:
1. регистрация (если нет учетки BTS);
2. листинг задач под скилл из гитхаба;
3. автоматизация внесения скилла;
4. автоматизация рассчета за скилл;
5. голосование за подрядчика по задаче;
6. голосование за приемку работы (арбитраж);

**Comment by codename-art** [comment]
API гитхаба, которое может пригодится для реализации https://developer.github.com/v3/issues/comments/

**Comment by nat-brit** [comment]
Идею с ботом поддерживаю.
> листинг задач под скилл из гитхаба;

Они же не автоматически будут подгружаться? кто их будет заносить в бот?

> автоматизация внесения скилла; автоматизация рассчета за скилл;
куда, если нет учетки в BTS?

> голосование за подрядчика по задаче;
> голосование за приемку работы (арбитраж);

Это тоже в боте надо? кто будет голосовать? Хотя иметь голосовалку всегда полезно, в любом раскладе:)  Если не будем голосовать по приемке задач в боте, то там можно оставлять только отметку - типа задача была принята и оплачена. Исполнителю - плюс в карму - и рейтинг пусть растет. Рейтинг исполнителей нужно добавить.

**Comment by cptn-solo** [comment]
@nat-brit  @LastWarrior 
> Рейтинг исполнителей нужно добавить.

@LastWarrior вот и всплыли твои токены репутации ;) подключайся

> Это тоже в боте надо? кто будет голосовать? 

Это кажется интуитивным. Нужно строить workflow как на постановку задачу в работу (за исполнителя), так и за приемку работы у него. Со стороны БЧ оплату можно подтверждать  мультиподписью, как это сделано по управленческим учеткам уже сейчас. Однако мнение сообщества или команды на предмет качества реализации в любом случае приветствуется. В пределе рейтинг по хабу должен приводить к оплате, но это не обязательно пихать в MVP

> Они же не автоматически будут подгружаться? кто их будет заносить в бот?

автоматом через API

Собственно, наши регламенты [тут](https://github.com/u-transnet/info/wiki/2.3.-%D0%A0%D0%B5%D0%B3%D0%BB%D0%B0%D0%BC%D0%B5%D0%BD%D1%82-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B8-%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B7%D0%B0%D0%B4%D0%B0%D1%87-(issue)) (общее) и [тут](https://github.com/u-transnet/info/wiki/2.2.-%D0%A0%D0%B5%D0%B3%D0%BB%D0%B0%D0%BC%D0%B5%D0%BD%D1%82-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81%D0%BE-SKILL-%D0%B2-%D1%80%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D1%8F%D1%85-u-transnet) (скилл)

**Comment by nat-brit** [comment]
@kkrupovich  @LastWarrior 
А рейтинг от чего будет зависеть?

> автоматом через API

А откуда? не все  же подряд.. Кажется, поняла:) Из репозитория "Задачи, ищущие исполнителя"?

**Comment by cptn-solo** [comment]
@nat-brit 

> куда, если нет учетки в BTS?

Регистрация тоже прекрасно автоматизируется, faucet можно эксплуатировать в хвост и в гриву, хоть наш (и регистрировать под себя, под u-tech), хоть рудекса, хоть OL

> А откуда? не все же подряд.. Кажется, поняла:) Из репозитория "Задачи, ищущие исполнителя"?

Помнишь лейблы у задач? ;) Вот они могут быть твоими собственными, как например #skilled# и #paid#
Ну и выгребать весь "Contribute" тоже можно в отдельный раздел. Можно же организовывать даже задачи по группам, внутри групп - приоритеты - как на досках проектов мы делаем. 

> А рейтинг от чего будет зависеть?

Заметь, рейтинг не я предложил :) Но мы как-то с @LastWarrior сидели и обсуждали эту тему, и мне помнится он предложил просто их накапливать за выполненные задачи. Это токен, третий - dev, dev.skill, dev.lvl - можно этот lvl непосредственно привязывать к ставке даже :) но это утопично несколько. @rossul что думаешь насчет этого всего ? Как бы ты систему рейтингов для ресурсного пула (пул разработчиков, команд) организовал, если бы у тебя была такая возможность ? В графене она просто есть, можно этих токенов создавать - хоть все пространство имен (разделитель - точка).

**Comment by ghost** [comment]
@kkrupovich 
Готов поучаствовать, тут больше frontend по разработке, но если понадобится REST API или что-то на python обрабатывать фоном, то я могу помочь с этим направлением. Потребности будут зависеть от того, что вы напланите и от результатов обсуждений с frontend разработчиками, они то и скажут что им не хватать будет касаемо API.

**Comment by ghost** [comment]
@kkrupovich 
Пропустил фразу telegram bot, frontend(а) не будет значит, тем не менее если API какая потребуется или помощь на python готов подключиться.

**Comment by nat-brit** [comment]
@kkrupovich @mparkhomenko 
>  можно этот lvl непосредственно привязывать к ставке даже. но это утопично несколько

Это не утопично. Рейтинг может зависеть от нескольких параметров: 1 балл за каждую задачу, плюс балл по ставке (есть задачи простые и их много), а есть одна сложная - рейтинг должен учитывать сложность (еще один параметр). 

> Пропустил  фразу telegram bot, frontend(а) не будет значит,

Думаю, фронтэнд будет обязательно, но позже, его нужно додумывать, когда получим первые результаты при использовании бота. Когда поймем, в каком порядке и в каком виде (и под какую ЦА) что должно выглядеть.

**Comment by EvgeniyPolyakov** [comment]
могу подключиться. пока я думаю что надо делать в связке фронтэнд -> бот, фронт для удобства как надстройка, потому что все же проще форму забить юзеру (причем часть данных уже введена 1 раз, например имя в гите), чем вводить в бот данные каждый раз. Но надо доизучить бот-функционал, надо сопоставить с нашими задачами - возможно бэк от @mparkhomenko  может понадобится в некоторых местах.

@kkrupovich где удобней рисовать схемы? :)

**Comment by cptn-solo** [comment]
[![](https://api.gh-polls.com/poll/01C4S9TRHPXV8KAAH21CVH1NNV/Telegram%20bot)](https://api.gh-polls.com/poll/01C4S9TRHPXV8KAAH21CVH1NNV/Telegram%20bot/vote)
[![](https://api.gh-polls.com/poll/01C4S9TRHPXV8KAAH21CVH1NNV/Web%20app)](https://api.gh-polls.com/poll/01C4S9TRHPXV8KAAH21CVH1NNV/Web%20app/vote)
[![](https://api.gh-polls.com/poll/01C4S9TRHPXV8KAAH21CVH1NNV/Github%20app)](https://api.gh-polls.com/poll/01C4S9TRHPXV8KAAH21CVH1NNV/Github%20app/vote)

**Comment by cptn-solo** [comment]
@mparkhomenko 
> Пропустил фразу telegram bot, frontend(а) не будет значит,

@nat-brit
> Думаю, фронтэнд будет обязательно, но позже, ...  когда получим первые результаты при использовании бота. Когда поймем, в каком порядке и в каком виде (и под какую ЦА) что должно выглядеть.

 @EvgeniyPolyakov @jackal1527 @mparkhomenko 

Начнем с макета, wire-frame, чтобы понять какая информация у нас есть по задачам и чего мы хотим с ней делать - обсудили с  @jackal1527 предварительно, получим нулевую итерацию для наглядности и будем развивать. 
Есть еще вариант запилить это все в виде github app - у хаба есть SDK для разработки [plugin-ов](https://github.com/u-transnet/codebase/settings/installations). Надо смотреть, исследовать. Я предварительно глянул - интересно.

@EvgeniyPolyakov
> где удобней рисовать схемы? :)

мы рисуем в draw.io, мокапы интерфейсов @jackal1527 может сделать в axure

**Comment by alecvert** [comment]
@kkrupovich @nat-brit @EvgeniyPolyakov думаете рейтинг это все ? Пишу с мобильного. Рейтинн - это прежде всего как приняли/оценили выполненные кандидатом задачи те, кто ставили задачи. Т к они лучше всего понимают какой результат достигнуть. Рейтинг оценить нужно в % шкале думаю от 1 до 100

**Comment by jackal1527** [comment]
Начали думать над таск-менеджером
Ссылка на [Axure](https://ak01eu.axshare.com)

Block #23966612
Transfer
From | jackal1527
To | utd-ux
Quantity | 200.00000 UTDEV.SKILL
Смотрим: понедельник 30_01_2018
@kkrupovich

**Comment by cptn-solo** [comment]
@jackal1527 уходим в реорганизацию процесса (jira) и [User Story](https://github.com/u-transnet/UT-WORKS/issues/1)

BLOCK #23973016

TRANSFER |  
-- | --
From | utd-ux
To | jackal1527
Quantity | 200.00000 UTDEV
