### ISSUE TITLE
Мигрировать transnet.space домен на наше docker-compose приложение

### ISSUE THREAD

**Issue by ghost** [u-transnet/codebase#50]
Пришли [отсюда](https://github.com/u-transnet/codebase/issues/28)
Еще нужен день чтобы аккуратно поднять через него все на нашем домене через https, развести nginx сайта от зоопарка ноды и при этом как то не посеять данные ноды

**Comment by ghost** [comment]
BLOCK #23848095
map-13
150UTDEV.SKILL
До вечера 25.01.18

**Comment by cptn-solo** [comment]
@mparkhomenko а где ты все это раскапываешь? Как вообще процесс происходит?

**Comment by ghost** [comment]
@kkrupovich 
[Документация](https://docs.docker.com/compose/) по docker compose.
Не понятные моменты гуглю.
Наращивал приложение по 1 контейнеру, пока не собрал в кучу ноду, фасет, гуи, веб сервер.
Сейчас очевидно, что master ветка и ветка под деплой на наш домен будут немного отличаться в связи с тем, что у нас там еще рядом сайт хостится и зоопарк на не стандартном порту 10443.

**Comment by ghost** [comment]
@kkrupovich мигрировал.
[transnet.space wallet](https://transnet.space:10443)
[Ветка](https://github.com/u-transnet/dockerfiles/commit/e04c9408e8441730827fa886be5cabf828e2595b), которая не будет заходить в master.

**Comment by cptn-solo** [comment]
@mparkhomenko 
> [Ветка](https://github.com/u-transnet/dockerfiles/commit/e04c9408e8441730827fa886be5cabf828e2595b), которая не будет заходить в master.

Можешь пояснить?

**Comment by ghost** [comment]
@kkrupovich 
Эта ветка была создана, потому что на нашем домене не стандартные порты и по соседству крутится сайт на стандартных. В ней специфические для нашего дроплета изменения, которые, скорее всего, в будущем станут не актуальными.

**Comment by cptn-solo** [comment]
@mparkhomenko 
BLOCK #23961960

TRANSFER |  
-- | --
From | utd-core
To | map-13
Quantity | 150.00000 UTDEV
