### ISSUE TITLE
readme  для желающего поднять ноду

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/codebase#51]
Пришли из #28 

Необходимо написать что-то вроде руководства для домохозяйки - со ссылками для скачивания и описанием требований по железу и софту (дополним ссылками на рекомендуемые хостинги может даже)

@bellevich дружище, у тебя нет под рукой чего-нибудь похожего?

UP: может, вот [такое](https://github.com/blckchnd/DECENT-docker) что-то

**Comment by ghost** [comment]
BLOCK #23858844
map-13
150UTDEV.SKILL
На 27.01.18-28.01.18 на 1 день в сумме

**Comment by nat-brit** [comment]
@kkrupovich 
> UP: может, вот такое что-то

Это для домохозяйки???:))))

Как пример нашла [тут](https://golos.io/ru--golos/@primus/nastroika-nod-mainera-i-delegata-dlya-raboty-v-golose-rabochie-konfigi-i-poyasneniya-po-ustanovke) и [тут](https://golos.io/golosnode/@ruslan/podnyatie-nody-dlya-golosa-odnoi-strokoi)

**Comment by cptn-solo** [comment]
@nat-brit @mparkhomenko 
> Как пример нашла  [тут](https://golos.io/ru--golos/@primus/nastroika-nod-mainera-i-delegata-dlya-raboty-v-golose-rabochie-konfigi-i-poyasneniya-po-ustanovke) и [тут](https://golos.io/golosnode/@ruslan/podnyatie-nody-dlya-golosa-odnoi-strokoi)

 Истина где-то посередине, полагаю.

**Comment by ghost** [comment]
@kkrupovich 
https://github.com/u-transnet/dockerfiles/pull/11
[README.md](https://github.com/u-transnet/dockerfiles/blob/master/README.md)

**Comment by ghost** [comment]
@kkrupovich 
Думаю, позже будет еще итерация, когда по мере эксплуатации соберем пожелания, жалобы, недочеты, фидбек вобщем то.

**Comment by cptn-solo** [comment]
@mparkhomenko 
BLOCK #23969383

TRANSFER |  
-- | --
From | utd-core
To | map-13
Quantity | 150.00000 UTDEV
