### ISSUE TITLE
Развернуть ноду руками

### ISSUE THREAD

**Issue by ghost** [u-transnet/codebase#6]
Развернуть witness node на дроплете по мануалу
http://docs.bitshares.org/bitshares/tutorials/full-node-usage.html

**Comment by cptn-solo** [comment]
@mparkhomenko , а ты после того, как развернешь "руками" - будешь готовить докер (#9)?
Я к чему спрашиваю - скрипт для whitelisting'а актива (#11)  можно будет сразу после закрытия этой задачи думать, или ждать докер надо?

**Comment by cptn-solo** [comment]
@mparkhomenko пару слов для протокола и закрывай.

**Comment by ghost** [comment]
@kkrupovich 
[Развертка witness node BitShares и CLI Wallet на linux машине из исходников](https://github.com/u-transnet/codebase/wiki/%D0%A0%D0%B0%D0%B7%D0%B2%D0%B5%D1%80%D1%82%D0%BA%D0%B0-witness-node-BitShares-%D0%B8-CLI-Wallet-%D0%BD%D0%B0-linux-%D0%BC%D0%B0%D1%88%D0%B8%D0%BD%D0%B5-%D0%B8%D0%B7-%D0%B8%D1%81%D1%85%D0%BE%D0%B4%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2)
