### ISSUE TITLE
Сделать Dockerfile

### ISSUE THREAD

**Issue by ghost** [u-transnet/codebase#8]
Сделать Dockerfile и обкатать на своей тачке локально

**Comment by cptn-solo** [comment]
@mparkhomenko @UspenskyDritry что у нас в итоге с докером? будет, нет?

**Comment by ghost** [comment]
@kkrupovich 
[Dockerfile](https://github.com/u-tech-bitshares/dockerfiles/blob/bitshares-core/bitshares-core/Dockerfile) доступен в репозитории
