### ISSUE TITLE
Запустить witness node через докер на дроплете

### ISSUE THREAD

**Issue by ghost** [u-transnet/codebase#9]
Развернуть witness node bitshares в docker на дроплете

**Comment by ghost** [comment]
BLOCK #22246773
map-13
300 UTDEV.SKILL
До вечера 02.12.2017

**Comment by ghost** [comment]
@kkrupovich 
BLOCK #22385522
map-13
+150 UTDEV.SKILL
До вечера 04.12.2017
Развернутая [нода](wss://transnet.tech:10443/ws) в данный момент синхронизируется
[Dockerfile](https://github.com/u-tech-bitshares/dockerfiles/blob/master/bitshares-core/Dockerfile) доступен в репозитории
Доработал [статью](https://github.com/u-transnet/codebase/wiki/%D0%A0%D0%B0%D0%B7%D0%B2%D0%B5%D1%80%D1%82%D0%BA%D0%B0-witness-node-BitShares-%D0%B8-CLI-Wallet-%D0%BD%D0%B0-linux-%D0%BC%D0%B0%D1%88%D0%B8%D0%BD%D0%B5-%D0%B8%D0%B7-%D0%B8%D1%81%D1%85%D0%BE%D0%B4%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2), раздел _Развертка через Docker_

**Comment by cptn-solo** [comment]
BLOCK #22419150
TRANSFER |  
From | utd-core
To | map-13
Quantity | 450.00000 UTDEV

Спасибо!
